- hosts: all
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: update repositories
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

  tasks:
    - import_tasks: tasks/docker.yaml