---
# tasks/portainer.yaml
- name: Install Pip package manager for Python 3
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present

- name: Install Python Docker module for Ansible
  ansible.builtin.pip:
    name: docker
    state: present

- name: Create Portainer data volume
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: Deploy Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env:
      TZ: "Europe/Madrid"
